apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.env }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.env }}-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        env:
        - name: "TOKEN_SECRET"
          valueFrom:
            secretKeyRef:
              name: secret-token
              key: secret_value
              optional: false # same as default; "mysecret" must exist
        - name: "API_PORT"
          value: "3000"
        - name: "JWT_HEADER_NAME"
          value: "x-jwt-kwy"
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 512M
            cpu: 0.25
          limits:
            memory: 1024M
            cpu: 0.5