apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.env }}-team-backend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: {{ .Values.env }}-team-backend
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: teams/team-backend/{{ .Values.env }}
    helm:
      parameters:
      - name: spec.ingress.hostBack
        value: {{ .Values.spec.ingress.hostBack }}
      - name: env
        value: {{ .Values.env }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
